# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8)),
                ('owner', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
    ]
